version: "2"

run:
  timeout: 5m
  build-tags:
    - lint
    - codeanalysis
linters:
  settings:
    staticcheck:
      checks:
        - all
        - -QF1001
        - -QF1003
        - -ST1000
        - -ST1003
        - -ST1005
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
