// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package meshdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminKey struct {
	ID        int64     `json:"id"`
	MeshID    int64     `json:"mesh_id"`
	PublicKey []byte    `json:"public_key"`
	KeyName   *string   `json:"key_name"`
	AddedBy   int64     `json:"added_by"`
	CreatedAt time.Time `json:"created_at"`
}

type Mesh struct {
	ID             int64       `json:"id"`
	OwnerID        int64       `json:"owner_id"`
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	LoraRegion     *string     `json:"lora_region"`
	ModemPreset    *string     `json:"modem_preset"`
	FrequencySlot  pgtype.Int4 `json:"frequency_slot"`
	HopLimit       pgtype.Int4 `json:"hop_limit"`
	TxPower        pgtype.Int4 `json:"tx_power"`
	ChannelNum     pgtype.Int4 `json:"channel_num"`
	UsePreset      bool        `json:"use_preset"`
	ConfigDefaults []byte      `json:"config_defaults"`
}

type MeshAccess struct {
	ID          int64     `json:"id"`
	MeshID      int64     `json:"mesh_id"`
	UserID      int64     `json:"user_id"`
	AccessLevel string    `json:"access_level"`
	GrantedBy   *int64    `json:"granted_by"`
	CreatedAt   time.Time `json:"created_at"`
}

type MeshChannel struct {
	ID           int64     `json:"id"`
	MeshID       int64     `json:"mesh_id"`
	ChannelIndex int32     `json:"channel_index"`
	ChannelRole  string    `json:"channel_role"`
	Psk          []byte    `json:"psk"`
	ChannelName  *string   `json:"channel_name"`
	Settings     []byte    `json:"settings"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Node struct {
	ID                   int64       `json:"id"`
	MeshID               int64       `json:"mesh_id"`
	HardwareID           string      `json:"hardware_id"`
	Name                 string      `json:"name"`
	LongName             string      `json:"long_name"`
	Role                 *string     `json:"role"`
	PublicKey            *string     `json:"public_key"`
	PrivateKey           *string     `json:"private_key"`
	LastSeen             *time.Time  `json:"last_seen"`
	Status               *string     `json:"status"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	AppliedName          *string     `json:"applied_name"`
	AppliedLongName      *string     `json:"applied_long_name"`
	AppliedRole          *string     `json:"applied_role"`
	AppliedPublicKey     *string     `json:"applied_public_key"`
	AppliedPrivateKey    *string     `json:"applied_private_key"`
	AppliedUnmessageable pgtype.Bool `json:"applied_unmessageable"`
	Unmessageable        bool        `json:"unmessageable"`
	ConfigAppliedAt      *time.Time  `json:"config_applied_at"`
	PendingChanges       bool        `json:"pending_changes"`
	NodeNum              *int64      `json:"node_num"`
	DeviceID             []byte      `json:"device_id"`
	FirmwareVersion      *string     `json:"firmware_version"`
	HwModel              pgtype.Int4 `json:"hw_model"`
	ShortName            *string     `json:"short_name"`
	RawDeviceConfig      []byte      `json:"raw_device_config"`
	ConfigOverrides      []byte      `json:"config_overrides"`
	ConfigImportedAt     *time.Time  `json:"config_imported_at"`
}

type NodeAdminKey struct {
	ID         int64     `json:"id"`
	NodeID     int64     `json:"node_id"`
	AdminKeyID int64     `json:"admin_key_id"`
	AppliedAt  time.Time `json:"applied_at"`
	IsCurrent  bool      `json:"is_current"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserApiKey struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	KeyHash    string     `json:"key_hash"`
	KeyName    string     `json:"key_name"`
	ExpiresAt  *time.Time `json:"expires_at"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
}
