// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package meshdb

import (
	"time"
)

type Mesh struct {
	ID          int64     `json:"id"`
	OwnerID     int64     `json:"owner_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MeshAccess struct {
	ID          int64     `json:"id"`
	MeshID      int64     `json:"mesh_id"`
	UserID      int64     `json:"user_id"`
	AccessLevel string    `json:"access_level"`
	GrantedBy   *int64    `json:"granted_by"`
	CreatedAt   time.Time `json:"created_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
