// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package meshdb

import (
	"context"
)

type Querier interface {
	CheckUserMeshAccess(ctx context.Context, arg CheckUserMeshAccessParams) (string, error)
	CreateMesh(ctx context.Context, arg CreateMeshParams) (Mesh, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMesh(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	GetMeshAccess(ctx context.Context, arg GetMeshAccessParams) (MeshAccess, error)
	GetMeshByID(ctx context.Context, id int64) (Mesh, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserSessions(ctx context.Context, userID int64) ([]Session, error)
	GrantMeshAccess(ctx context.Context, arg GrantMeshAccessParams) (MeshAccess, error)
	ListMeshAccessByMesh(ctx context.Context, meshID int64) ([]ListMeshAccessByMeshRow, error)
	ListMeshAccessByUser(ctx context.Context, userID int64) ([]ListMeshAccessByUserRow, error)
	ListMeshesByOwner(ctx context.Context, ownerID int64) ([]Mesh, error)
	ListMeshesByUser(ctx context.Context, userID int64) ([]Mesh, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeMeshAccess(ctx context.Context, arg RevokeMeshAccessParams) error
	UpdateMesh(ctx context.Context, arg UpdateMeshParams) (Mesh, error)
	UpdateMeshAccess(ctx context.Context, arg UpdateMeshAccessParams) (MeshAccess, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
